---
- name: Set Up Load Balancer
  hosts: loadbalancers
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: latest

    - name: Deploy HAProxy configuration
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

    - name: Ensure HAProxy is running
      service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted